config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/one", to: "one#index"
  get "/one/turbo-frame", to: "one#turbo_frame_form"
  post "/one/turbo_frame_submit", to: "one#turbo_frame_submit"
  post "/one/post_something", to: "one#post_something"

  get "/two", to: "one#two"
  post "/one/post_message", to: "one#post_message"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/one_controller.rb
class OneController < ApplicationController

  def index
  end

  def turbo_frame_form
  end

  def turbo_frame_submit
    extracted_anynumber = params[:any][:anynumber]
    render :turbo_frame_form, status: :ok, locals: {anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }
  end

  def post_something
    respond_to do |format|
      format.turbo_stream {  }
    end
  end

  # page 2

  def two
  end

  def post_message
    respond_to do |format|
      format.turbo_stream {  }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<p>Home sweet home</p>

<ul>
  <li><%= link_to "One", one_path %></li>
  <li><%= link_to "Two", two_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZeroRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/one/index.html.erb
<h1>Page One</h1>

<p>This is page one</p>

<h3>Turbo Frame</h3>

<%= link_to "Root", root_path %>

<%= turbo_frame_tag 'anyframe' do %>
  <div>
      <h4>One page view</h4>
      <%= form_with scope: :any, url: one_turbo_frame_submit_path, local: true do |form| %>
          <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
          <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
          <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
      <% end %>
  <div>
<% end %>

<h3>Turbo Stream</h3>

<div style="margin-top: 3rem;">
  <%= form_with scope: :any, url: one_post_something_path do |form| %>
      <%= form.submit 'Post something' %>
  <% end %>
  <turbo-frame id="messages">
    <div>An empty message</div>
  </turbo-frame>
</div>

app/views/one/post_something.turbo_stream.erb
<turbo-stream action="append" target="messages">
  <template>
    <div id="message_1">This changes the existing message!</div>
  </template>
</turbo-stream>

app/views/one/turbo_frame_form.html.erb
<section>

  <%= turbo_frame_tag 'anyframe' do %>

    <div>
        <h4>Frame view</h4>
        <%= form_with scope: :any, url: one_turbo_frame_submit_path, local: true do |form| %>
            <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
            <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
            <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
        <% end %>
    </div>
    <div>
      <h2>Data of the view</h2>
      <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre>
    </div>

  <% end %>

</section>

app/views/one/two.html.erb
<h1>Page Two</h1>

<p>This is page Two</p>
<%= link_to "Root", root_path %>

<h3>Stimulus</h3>

<div style="margin-top: 2rem;">
  <%= form_with scope: :any, url: one_post_message_path do |form| %>
      <%= form.submit 'Post something' %>
  <% end %>
  <turbo-frame id="messages">
    <div>An empty message</div>
  </turbo-frame>
</div>

<div style="margin-top: 2rem;">
  <h2>Stimulus</h2>
  <div data-controller="hello">
    <input data-hello-target="name" type="text">
    <button data-action="click->hello#greet">
      Greet
    </button>
    <span data-hello-target="output">
    </span>
  </div>
</div>